apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          resources: {}
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: {{ .Values.containers.containerPort }}
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: {{ .Values.containers.containerPort }}
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: PORT
              value: {{ .Values.containers.containerPort | quote }}
          volumeMounts:
            - name: index-html
              mountPath: /tmp/html
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: index-html
          configMap:
            name: {{ printf "%s-html" .Chart.Name | quote }}
            defaultMode: 420
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
